# Generated by Django 3.1.7 on 2021-03-09 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SEL', 'Seller'), ('CAS', 'Cashier'), ('ACC', 'Accountant')], default='CAS', max_length=50, verbose_name='Role')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.TextField(null=True, verbose_name='Name client')),
                ('status', models.CharField(choices=[('NEWORD', 'New order'), ('PROC', 'Processed'), ('PAID', 'Paid')], default='NEWORD', max_length=20, verbose_name='Order status')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Date create')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordermanager.employee', verbose_name='Cashier')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name product')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Price product')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Date create')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(verbose_name='Date created')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordermanager.order', verbose_name='Order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordermanager.product', verbose_name='Ordered product'),
        ),
    ]
